package documentstorage;

/**
 *
 * @author podolak
 */
public enum ButtonType {
    CREATE_NEW_SOURCE,
    RANDOM_ID,
    CHECKOUT_SOURCE, CHECKOUT_LINK, CHECKOUT_TARGET,
    CHECKOUT_WITH_VERSION_NUMBER,
    FORWARD_TRANSFORMATION,
    UPDATE, COMMIT_TRIPLE, COMMIT_SOURCE, COMMIT_LINK, COMMIT_TARGET;
}
