/*
 * ApplicationSharingClient.java
 *
 * Created on 24. Juni 2007, 17:08
 */

package applicationSharing;

/**
 *
 * @author  podolak
 */
public class ApplicationSharingClientGUI extends javax.swing.JFrame {

    private ApplicationSharingClientController controller;

    /**
     * Creates new form ChatClient
     */
    public ApplicationSharingClientGUI() {
        initComponents();
    }

    /**
     * Creates new form ChatClient
     * @param controller
     */
    public ApplicationSharingClientGUI(ApplicationSharingClientController controller) {
        this.controller = controller;

        initComponents();

        execute.addActionListener(controller);
        command.addKeyListener(controller);

        if (controller != null && controller.getLocalName() != null && controller.getLocalNodeHandle() != null) {
            setTitle(controller.getLocalName() + " (" + controller.getLocalNodeHandle().getId() + ")");
        }
    }

    public String getCommandLine() {
        return command.getText();
    }

    public void clearCommandLine() {
        command.setText("");
    }

    public void addText(String text) {
        response.append(text + "\n");
        response.setCaretPosition(response.getText().length());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commandLabel = new javax.swing.JLabel();
        command = new javax.swing.JTextField();
        execute = new javax.swing.JButton();
        responseLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        response = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        commandLabel.setText("command");

        execute.setText("execute");

        responseLabel.setText("response");

        response.setColumns(20);
        response.setRows(5);
        scrollPane.setViewportView(response);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(commandLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(command, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(execute))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(responseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commandLabel)
                    .addComponent(execute)
                    .addComponent(command, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(responseLabel)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField command;
    private javax.swing.JLabel commandLabel;
    private javax.swing.JButton execute;
    private javax.swing.JTextArea response;
    private javax.swing.JLabel responseLabel;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}